apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: zipkin
          image: 045810265680.dkr.ecr.us-east-1.amazonaws.com/petclinic/zipkin:9caf48e
          ports:
            - containerPort: 9411
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: petclinic
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
