apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway-policy
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: config-server
      ports:
        - protocol: TCP
          port: 8888
    - to:
        - podSelector:
            matchLabels:
              app: discovery-server
      ports:
        - protocol: TCP
          port: 8761
    - to:
        - podSelector:
            matchLabels:
              app: customers-service
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              app: vets-service
      ports:
        - protocol: TCP
          port: 8083
    - to:
        - podSelector:
            matchLabels:
              app: visits-service
      ports:
        - protocol: TCP
          port: 8082
    - to:
        - podSelector:
            matchLabels:
              app: genai-service
      ports:
        - protocol: TCP
          port: 8084
    - to:
        - podSelector:
            matchLabels:
              app: zipkin
      ports:
        - protocol: TCP
          port: 9411
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
