apiVersion: v1
kind: ResourceQuota
metadata:
  name: petclinic-quota
  namespace: petclinic
spec:
  hard:
    # Total CPU across all pods in this namespace
    requests.cpu: "4500m"
    limits.cpu: "7000m"

    # Total memory across all pods in this namespace
    requests.memory: "6Gi"
    limits.memory: "8Gi"

    # Max number of pods allowed
    pods: "20"

    # Max number of secrets and configmaps
    secrets: "20"
    configmaps: "20"
