# This file defines the Kubernetes Deployment for the genai-service application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: genai-service
          image: 045810265680.dkr.ecr.us-east-1.amazonaws.com/petclinic/genai-service:9caf48e
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret      # matches what you created
                  key: api-key             # matches the secret key
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 768Mi
              cpu: 500m
        
 

