apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: "git"
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/PETCLINIC-PROJECT-GROUP-5/spring-petclinic-microservices-config"
