apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: api-gateway
          image: 045810265680.dkr.ecr.us-east-1.amazonaws.com/petclinic/api-gateway:9caf48e
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 768Mi
              cpu: 500m


